### ISSUE TITLE
Elasticsearch 2.0 compatibility

### ISSUE THREAD

**Issue by ksindi** [bonzanini/CheerMeApp-demo#1]
Great demo. I think the following needs to be changed in mappings.json for ES 2.0 compatibility:
- Key index_analyzer becomes analyzer
- The type styles can no longer have a property named "name" because it conflicts with beers's "name" field. Only way I see around this is to rename it to something else.

**Comment by bonzanini** [comment]
Thank you, I've updated the readme while I'm looking for some spare time to fix and test this. Cheers

**Comment by ksindi** [comment]
Pleasure. Let me know if you find a workaround for bullet point 2: it would be nice if type styles could keep the fieldname "name".
